language: php
dist: trusty
sudo: required
services:
  - docker
php:
  - 5.6
  - 7.0
  - 7.1

before_script:
  - docker pull robsonvn/couchdb-ssl
  - docker run -d -p 5984:5984 -p 6984:6984 robsonvn/couchdb-ssl
  - sleep 5
  - curl -X PUT localhost:5984/unittest
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
