name: rvm-api-cd

on:
  push:
    branches: 
      - stage
  pull_request:
    branches:
      - stage

jobs:
  deploy:
    name: deploy-to-aws
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@stage
      run: 
        echo $RVM_SSH_KEY > ssh_key.pem
        ssh -i ssh_key.pem $RVM_USERNAME@$RVM_MACHINE 
